### ISSUE TITLE
Translations for awesome-typst?

### ISSUE THREAD

**Issue by jcbhmr** [qjcg/awesome-typst#161]
I notice that there's a parallel project  https://github.com/typst-cn/awesome-typst-cn

Here's some existing awesome-$THING projects that do translations (to various degrees):
- https://github.com/alebcay/awesome-shell
- https://github.com/qazbnm456/awesome-web-security
- https://github.com/tiimgreen/github-cheat-sheet
- https://github.com/junnplus/awesome-python-books
- https://github.com/jaywcjlove/awesome-mac
- https://github.com/Kamigami55/awesome-chatgpt
- https://github.com/lightningminers/awesome-indie

I think it would be good for the Typst ecosystem to centralize all the awesome stuff on one repository with translations _in that one well-known repository_ instead of fragmenting across language-specific repositories. That's my opinion though, which is why I'm opening this issue 😊 to see if this is something that others want or if this isn't a priority.

What I'm proposing:
Merge https://github.com/typst-cn/awesome-typst-cn with this https://github.com/qjcg/awesome-typst repository.

cc @mintyfrankie @OrangeX4 @Liangdi @lucifer1004 from https://github.com/typst-cn/awesome-typst-cn contributors

**Comment by qjcg** [comment]
Hey @jcbhmr, thanks for opening this issue!

I personally love the idea of merging. It would be great to have all of these great Typst community resources in one place. 

Merging has the potential to at least somewhat reduce "drift" between the translations by keeping the different language versions closer together and increasing the chances community members will compare the two directly to keep them in sync.

@mintyfrankie @OrangeX4 @Liangdi @lucifer1004 what do you think?

**Comment by mintyfrankie** [comment]
Hi all,

Overall this can indeed be a great idea in my opinion. After all, we are talking about the same templates that are necessarily language-specific.Personally I'd love to contribute to merge or translate existing documents into the same repo to make this happen.

I see however two potential issues to sort out first in practice:

- the [Chinese equivalent repo](https://github.com/typst-cn/awesome-typst-cn) has about one third of templates that are indeed written for a specific purpose: you've got the very first section that are 100% templates for essays and theses of universities in China; to see if we are to maintain a separate section for their audience, or to keep them exclusively in the Chinese version of the merged repo.

- As you all might notice, the existing Chinese repo is maintained by an org [typst-cn](https://github.com/typst-cn), who seems to have the intention to develop a community that goes simply beyond the awesome repo. I am not de facto in the community, so it might be interesting to reach out to the founders or active members for more discussions. 

Whatsoever I think it is worthy of our efforts to bring two parallel communities together; I am interested to do more as a maintainer of multilingual template anyway!

**Comment by OrangeX4** [comment]
I also believe that the awesome-typst-cn repository should be merged into the awesome-typst repository, making it more convenient for updates and maintenance. I do have concerns about two issues:

The first issue is how to keep the Chinese and English versions in sync. One suggestion is to keep the newly added English content synchronized in the Chinese version, and then wait for contributors to translate it.

The second issue is also about how to differentiate between universal content and language-specific content. For example, awesome-typst-cn contains many Chinese templates for Chinese university papers, which definitely need to be maintained independently.

PS: Currently, the [typst-cn](https://github.com/typst-cn) organization does not have active maintainers. Therefore, a new organization, [typst-doc-cn](https://github.com/typst-doc-cn), has opened a new [awesome-typst-cn repository](https://github.com/typst-doc-cn/awesome-typst-cn) for maintenance.

**Comment by jcbhmr** [comment]
> The first issue is how to keep the Chinese and English versions in sync. One suggestion is to keep the newly added English content synchronized in the Chinese version, and then wait for contributors to translate it.

I don't think it necessarily needs to be _exactly_ translated. For instance, some things might make more sense to be Chinese-only. Example from Chinese docs: https://typst-doc-cn.github.io/docs/chinese/

> The first issue is how to keep the Chinese and English versions in sync. One suggestion is to keep the newly added English content synchronized in the Chinese version, and then wait for contributors to translate it.

This seems like a very good idea 👍

> The second issue is also about how to differentiate between universal content and language-specific content. For example, awesome-typst-cn contains many Chinese templates for Chinese university papers, which definitely need to be maintained independently.

I think that's OK. Locale-specific awesome stuff is great! The point of localizing the list I don't think is to 1-for-1 translate it but instead to _localize it_ and make it _better_ than just running the content through a translator service or whatever. In this case, I think Chinese templates and university papers on the zh readme is great!

> PS: Currently, the [typst-cn](https://github.com/typst-cn) organization does not have active maintainers. Therefore, a new organization, [typst-doc-cn](https://github.com/typst-doc-cn), has opened a new [awesome-typst-cn repository](https://github.com/typst-doc-cn/awesome-typst-cn) for maintenance.

👍

**Comment by mintyfrankie** [comment]
We are making some progress here!

Surprised to learn that [typst-cn](https://github.com/typst-cn) doesn't have active maintainers anymore. Yet it seems like @OrangeX4 is also one of the maintainers for the new [typst-doc-cn](https://github.com/typst-doc-cn), so are we talking about transitioning to a single repository, or keeping these two repo paralleled?

I'd be happy to help if any next-steps can be identified.

**Comment by jcbhmr** [comment]
@mintyfrankie for concrete actions to take, here's some ideas:
- [x] open a PR to merge content from https://github.com/typst-doc-cn/awesome-typst-cn to this repo #162 
- [ ] open a PR to say "moved to README_zh.md in this repo" in https://github.com/typst-doc-cn/awesome-typst-cn
- [ ] (maybe) open a PR to say "new list here" in https://github.com/typst-cn/awesome-typst-cn ? or if that doesn't work an issue like https://github.com/typst-cn/awesome-typst-cn/issues/18

**Comment by OrangeX4** [comment]
I think that's good, and if awesome-typst agrees to this, I'll make typst-doc-cn/awesome-typst-cn archived, then we only need to maintain awesome-typst :-)
